# This is a basic workflow to help you get started with Actions

name: PR - Publish Preview

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  expo-preview:
    uses: Kingstinct/utils/.github/workflows/expo-preview.yml@main
    with:
      expo_release_channel: pr-${{ github.event.number }}
      expo_app_slug: healthkit-example-expo
      env_inline: CUSTOM_NAME=pr-${{ github.event.number }}
      expo_organisation_or_user_slug: react-native-healthkit
      working_directory: ./example-expo
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
   eas-ios:
    # The type of runner that the job will run on
    uses: Kingstinct/utils/.github/workflows/eas-build.yml@main
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    with:
      platform: ios
      build_profile: development
      expo_organisation_or_user_slug: react-native-healthkit
      always_run: true