# This is a basic workflow to help you get started with Actions

name: Test and Publish Client PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  expo-publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.0

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      
    - name: Install deps
      run: yarn

    - name: Test
      run: yarn test

    - name: Expo GitHub Action
      uses: expo/expo-github-action@v7
      with:
        # Your Expo username, for authentication.
        token: ${{ secrets.EXPO_TOKEN }}
        expo-version: latest
        eas-version: latest
        # If Expo should be stored in the GitHub Actions cache (can be true or false)
        expo-cache: true # optional

    - name: Install deps
      run: cd example && yarn
    
    # Runs a set of commands using the runners shell
    - name: Publish
      run: cd example && CUSTOM_NAME=pr-${{ github.event.number }} expo publish --release-channel=pr-${{ github.event.number }}

    - uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: Expo preview is ready for review, [it's available here](https://expo.dev/@kingstinct/react-native-healthkit-example?serviceType=classic&distribution=expo-dev-client&releaseChannel=pr-${{ github.event.number }}&scheme=exp%2Breact-native-healthkit-example).